events {
    worker_connections 1024;
}

http {
    upstream clientes_service {
        server servicio-clientes:8083;
    }

    upstream productos_service {
        server servicio-productos:8080;
    }

    upstream pedidos_service {
        server servicio-pedidos:8082;
    }

    server {
        listen 8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Clientes (.NET)
        location ~* ^/api/clientes(/.*)?$ {
            proxy_pass http://clientes_service;
        }

        # Productos (Java/Spring)
        location ~* ^/api/productos(/.*)?$ {
            proxy_pass http://productos_service;
        }

        # Pedidos (Go) - Redirige /api/pedidos a /pedidos en el contenedor de Go
        location /api/pedidos {
            rewrite ^/api/pedidos/(.*) /$1 break;
            rewrite ^/api/pedidos$ /pedidos break;
            proxy_pass http://pedidos_service;
        }

        location / {
            return 200 '{"status": "API Gateway activo", "version": "1.0"}';
            add_header Content-Type application/json;
        }
    }
}